yukishiozaki/mynote

- app/Http/Controllers/NotesController.php
- public/js/app.js
- resources/js/app.js
- resources/js/components/MemoAreaComponent.vue
- resources/views/notes/list.blade.php
> メモフォーカス移動で編集されるようにする機能の実装

- public/js/app.js
- resources/js/components/MemoAreaComponent.vue
- resources/views/notes/list.blade.php
> 改行があるデータが正しく表示されない不具合を修正

- resources/views/notes/list.blade.php
> backgroud変更

- app/Http/Controllers/ColorsController.php
- app/Http/Controllers/WallpapersController.php
> Second test/branch

- app/Http/Controllers/UsersController.php
- app/Http/Controllers/WallpapersController.php
- app/Models/User.php
- public/js/app.js
- resources/js/components/MemoAreaComponent.vue
- resources/lang/ja/validation.php
- resources/views/auth/register.blade.php
- resources/views/layouts/app.blade.php
- resources/views/notes/list.blade.php
- resources/views/users/edit.blade.php
- routes/web.php
> Profile編集画面作成

- app/Http/Controllers/UsersController.php
- app/Http/Controllers/WallpapersController.php
- app/Models/User.php
- resources/views/users/edit.blade.php
> User edit, wallpaper選択

- app/Http/Controllers/UsersController.php
> Controller内容復習

- app/Http/Controllers/UsersController.php
> 1129develop

- app/Http/Controllers/UsersController.php
- resources/views/notes/list.blade.php
> 1130develop

- app/Http/Controllers/UsersController.php
- public/css/app.css
- resources/sass/app.scss
- resources/views/layouts/app.blade.php
- resources/views/users/edit.blade.php
> 1201develop

- public/css/app.css
- resources/sass/app.scss
- resources/views/layouts/app.blade.php
- webpack.mix.js
> 1202develop

- public/css/app.css
- resources/sass/app.scss
- resources/views/layouts/app.blade.php
> 1203develop

- app/Http/Controllers/NotesController.php
- public/css/app.css
- resources/sass/app.scss
- resources/views/auth/login.blade.php
- resources/views/layouts/app.blade.php
> 1205develop

- public/css/app.css
- resources/sass/app.scss
- resources/views/layouts/app.blade.php
> 1206develop

- resources/views/notes/list.blade.php
> 1207develop-2

- resources/views/layouts/app.blade.php
- resources/views/users/edit.blade.php
> 1208develop

- public/css/app.css
- resources/sass/app.scss
- resources/views/layouts/app.blade.php
- resources/views/notes/list.blade.php
> 1211develop

- resources/views/notes/list.blade.php
> 1214develop

- app/Http/Controllers/NotesController.php
- resources/views/notes/list.blade.php
- routes/web.php
> 1214develop_second

- app/Http/Controllers/NotesController.php
- config/database.php
- resources/views/notes/list.blade.php
- routes/web.php
> 1215develop

- resources/views/notes/list.blade.php
> 1215develop_second

- app/Http/Controllers/NotesController.php
> completeで更新したいNoteをfindした後にNewしているのでinsertしようとしてエラーになるバグを修正

- resources/views/notes/list.blade.php
- routes/web.php
Complete listにアクセスした時、[MethodNotAllowedHttpException No message]というエラーが出てしまいます；；
NotesControllerのdeleteアクション、Viewファイルはlist.blade.phpです。
> 1216develop

- app/Http/Controllers/Auth/RegisterController.php
- app/Http/Controllers/NotesController.php
- database/migrations/2019_12_18_111058_set_wallpaper_id_default_to_users_table.php
- resources/views/notes/list.blade.php
- routes/web.php
- vendor/composer/autoload_classmap.php
- vendor/composer/autoload_static.php
> fix #24 & #25

- app/Http/Controllers/UsersController.php
- resources/views/users/edit.blade.php
> 1219develop

- resources/views/users/edit.blade.php
> 1220develop

- app/Http/Controllers/Auth/RegisterController.php
- resources/lang/ja/validation.php
> 1222develop

- public/css/app.css
- resources/sass/app.scss
> 1224develop

- resources/sass/app.scss
- resources/views/layouts/app.blade.php
> 1225develop

- .gitignore
- routes/web.php
> 1229develop

- public/css/app.css
- resources/sass/app.scss
- routes/web.php
> 1231develop

- resources/views/notes/list.blade.php
> 0102develop

- app/Http/Controllers/ColorsController.php
- resources/sass/app.scss
> 0105develop

- app/Policies/TaskPolicy.php
> 0209develop
